version: 2.1
jobs:
  build_and_deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Clone code
          command: git clone https://github.com/aakashgoel2002/node-todo-cicd.git
      - run:
          name: Build image
          command: docker build -t node-todo-app .
      - run:
          name: Scan image
          command: echo Scanning Done  # Replace with actual scanning commands
      - run:
          name: Push image
          command: |
            docker tag node-todo-app ${DOCKERHUB_USER}/node-todo-app
            docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASS}
            docker push ${DOCKERHUB_USER}/node-todo-app:latest
      - run:
          name: Deploy
          command: docker-compose down && docker-compose up -d

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy
